### ISSUE TITLE
Set up call with Lesedi to discuss Bwabwata milestone

### ISSUE THREAD

**Issue by raquelalegre** [namibmap/IPPR#46]
We should set up another phone call like last time to talk to Lesedi about progress. What do you people think? Can someone create a doodle poll? I'm very likely not to be available before the CartoDB call, perhaps we can discuss both things in the same call?

(Edit by @missfunmi on 22 Nov):
### ToDo List
- [x] Set up Doodle poll: http://doodle.com/poll/t9kvuw3asy5u6zk2
- [x] Send out Doodle poll
- [x] Decide on a date: Most popular date was Tue 12/1/15 Evening with 4 confirmed Yes
- [x] Organise agenda: See below
- [x] Send calendar invite
- [x] Update wiki with notes & action items: https://github.com/namibmap/IPPR/wiki/ProjectMeetings
