### ISSUE TITLE
Organise face2face meeting for week 7th - 11th December

### ISSUE THREAD

**Issue by raquelalegre** [namibmap/IPPR#56]
(Edit by @missfunmi on 22 Nov):
### ToDo List
- [x] Set up Doodle poll: http://doodle.com/poll/n7is2ra4wd2d57ba
- [x] Send out Doodle poll
- [ ] Decide on a date
- [ ] Organise agenda
- [ ] Send calendar invite
- [ ] Update wiki with notes & action items: https://github.com/namibmap/IPPR/wiki/ProjectMeetings
