### ISSUE TITLE
Refactor front-end JavaScript code to use a modular design

### ISSUE THREAD

**Issue by missfunmi** [namibmap/IPPR#81]
The front end code on the license-holders page is quite unwieldy with all the new functions that have been recently added to `display-concessions-map.js` (see commits on #40). We need to rewrite it to be more modular.
## Tasks
- [x] Quick refresher read-up on the Module pattern at the links below (been a while...)
- [x] Research all framework options listed below to select one - Narrowed down to Angular 2.0 (which is [now in beta](http://angularjs.blogspot.com/2015/12/angular-2-beta.html) & stable for Production usage) and EmberJS.
- [x] Get familiar with Angular 2.0 via a sample project (e.g. [TodoMVC](http://todomvc.com/)) or a starter tutorial
- [x] Get familiar with Ember JS via a sample project (e.g. [TodoMVC](http://todomvc.com/)) or a starter tutorial
- [x] Evaluate ReactJS via a sample project (e.g. [TodoMVC](https://facebook.github.io/flux/docs/todo-list.html)) and investigate its pros and cons
- [x] Identify pros & cons of Angular 2.0 vs EmberJS based on personal experience with the sample project
- [x] Select a final framework to use for the project
- [x] Rewrite the concessions map implementation (#34) using the new framework or pattern
- [x] Rewrite the list selection feature (#40) using the new framework or pattern
- [ ] Rewrite the map highlight feature (#40) using the new framework or pattern
### Useful references for the Module pattern:
- [The Design of Code: Organizing JavaScript](http://alistapart.com/article/the-design-of-code-organizing-javascript)
- [How Do You Structure JavaScript? The Module Pattern Edition](https://css-tricks.com/how-do-you-structure-javascript-the-module-pattern-edition/)
- [jQuery's Code Organization Concepts](https://learn.jquery.com/code-organization/concepts/)
- [Learning JavaScript Design Patterns: The Module Pattern](http://addyosmani.com/resources/essentialjsdesignpatterns/book/#modulepatternjavascript)
- [Patterns For Large-Scale JavaScript Application Architecture](http://addyosmani.com/largescalejavascript/)
### JavaScript Frameworks

We should also look into using an MVC framework that supports two-way data binding. Here are some options to consider:
- ~~[Angular 1.x](https://angularjs.org/)~~ -- Being replaced by Angular 2.0
- [Angular 2.0](https://angular.io/)
- [Ember](http://emberjs.com/)
- ~~[Aurelia](http://aurelia.io/)~~ -- Not wide enough of an adoption base or support/developer network
